'use strict';
/* Английский словарь Игротеки (генерируется build-скриптом). */
window.I18N_EN = {
  words: {
 "% поля": "% of field",
 "+25 БОНУС": "+25 BONUS",
 "/ тап — удар молотком": "/ tap — hammer strike",
 "15×15": "15×15",
 "16×16 · 40 мин": "16×16 · 40 mines",
 "1–3 — ставка, H — ещё, S — хватит": "1–3 — bet, H — hit, S — stand",
 "1–4 или клик по цвету": "1–4 or click a color",
 "1–4 — выбрать ответ": "1–4 — pick an answer",
 "1–9 на клавиатуре": "1–9 on the keyboard",
 "20 мишеней по одной — сбей все за минимальное время": "20 targets one by one — hit them all in minimal time",
 "20 мишеней по одной. Сбей все за минимальное время": "20 targets, one at a time. Hit them all in minimal time",
 "2048 — Игротека": "2048 — Igroteka",
 "3 жизни": "3 lives",
 "3 полосы": "3 lanes",
 "3 режима · комбо": "3 modes · combo",
 "3 сложности": "3 difficulties",
 "30 секунд на раунд. Кроты выскакивают из нор — клик или тап, чтобы прихлопнуть.\nОбычный крот — +1, золотой хомяк — +3.\nК концу раунда кроты появляются чаще и прячутся быстрее.": "30 seconds per round. Moles pop out of holes — click or tap to whack them.\nA regular mole — +1, a golden hamster — +3.\nTowards the end moles appear faster and hide quicker.",
 "30 секунд, чтобы прихлопнуть как можно больше кротов": "30 seconds to whack as many moles as you can",
 "30 секунд: успей прихлопнуть как можно больше кротов": "30 seconds: whack as many moles as you can",
 "30×16 · 99 мин": "30×16 · 99 mines",
 "4 дорожки": "4 lanes",
 "4 линии за раз — «тетрис» ×8 очков": "4 lines at once — “tetris” ×8 points",
 "45 мини-игр · всё работает офлайн · рекорды сохраняются": "50 mini-games · fully offline · records are saved",
 "5 раундов: дожидайся зелёного и кликай как можно быстрее": "5 rounds: wait for green and click as fast as you can",
 "5 раундов: как только фон зеленеет — жми": "5 rounds: as soon as the background turns green — click",
 "50 мини-игр · всё работает офлайн · рекорды сохраняются": "50 mini-games · fully offline · records are saved",
 "6 попыток": "6 tries",
 "6 уровней": "6 levels",
 "60 секунд": "60 seconds",
 "60 секунд: решай примеры, выбирая ответ из четырёх (клавиши 1–4).\nСерия верных ответов растит комбо — чем оно выше, тем больше очков за каждый пример.\nОшибка сбрасывает комбо и отнимает очко. После 15 очков появляются примеры на умножение.": "60 seconds: solve problems by picking one of four answers (keys 1–4).\nA streak of correct answers grows your combo — the higher it is, the more points per problem.\nAn error resets the combo and costs a point. After 15 points multiplication joins in.",
 "6×6 · 12 уровней": "6×6 · 12 levels",
 "7 попыток": "7 tries",
 "90 секунд": "90 seconds",
 "9×9 · 10 мин": "9×9 · 10 mines",
 "D F J K — дорожки": "D F J K — lanes",
 "Enter — заново": "Enter — restart",
 "Enter — заново · Esc — в меню": "Enter — restart · Esc — menu",
 "Flappy": "Flappy",
 "Flappy — Игротека": "Flappy — Igroteka",
 "R — заново": "R — restart",
 "Z — отмена · R — заново · свайпы": "Z — undo · R — restart · swipes",
 "minimax ИИ": "minimax AI",
 "· ИИ": "· AI",
 "· ничьи": "· draws",
 "· открыто": "· open",
 "· ходов": "· moves",
 "АИМ": "AIM TRAINER",
 "АРКАНОИД": "BREAKOUT",
 "АСТЕРОИДЫ": "ASTEROIDS",
 "АЭРОХОККЕЙ": "AIR HOCKEY",
 "Авария на скорости": "Crash at speed",
 "Аим": "Aim Trainer",
 "Аим — Игротека": "Aim Trainer — Igroteka",
 "Аркада": "Arcade",
 "Арканоид": "Breakout",
 "Арканоид — Игротека": "Breakout — Igroteka",
 "Артиллерийская дуэль с ИИ: угол, сила и переменный ветер": "Artillery duel vs AI: angle, power and shifting wind",
 "Астероиды": "Asteroids",
 "Астероиды — Игротека": "Asteroids — Igroteka",
 "Аэрохоккей": "Air Hockey",
 "Аэрохоккей — Игротека": "Air Hockey — Igroteka",
 "БАШНЯ": "STACK TOWER",
 "БУМ!": "BOOM!",
 "БЫКИ И КОРОВЫ": "BULLS & COWS",
 "Банк": "Bank",
 "Банк опустел. Новая сотня уже ждёт": "The bank ran dry. A fresh hundred awaits",
 "Башня": "Stack Tower",
 "Башня перенесена!": "Tower moved!",
 "Башня рухнула": "The tower collapsed",
 "Башня собрана!": "Tower complete!",
 "Башня — Игротека": "Stack Tower — Igroteka",
 "Беги по пустыне, перепрыгивай кактусы и пригибайся под птицами": "Run the desert, leap over cacti and duck under birds",
 "Беги по пустыне, прыгай через кактусы, пригибайся под птицами": "Run the desert, jump cacti, duck under birds",
 "Бери любое число палочек из одного ряда. Кто возьмёт последнюю — тот победил": "Take any number of sticks from one row. Whoever takes the last one wins",
 "Бери палочки из рядов. Кто возьмёт последнюю — победил": "Take sticks from rows. Whoever takes the last one wins",
 "Блок движется влево-вправо. Клик, тап или Пробел — сбросить его на башню.\nВсё, что свисает над краем, отрезается — башня становится уже. Промах целиком — конец.\nИдеальная укладка (без смещения) слегка расширяет блок и даёт бонус. Скорость растёт с высотой.": "The block slides left and right. Click, tap or Space — drop it onto the tower.\nWhatever hangs over the edge is sliced off — the tower gets narrower. A complete miss ends the run.\nA perfect stack (no offset) slightly widens the block and gives a bonus. Speed grows with height.",
 "Блоки": "Bricks",
 "Блэкджек против дилера: набери ближе к 21 и не пережги": "Blackjack vs the dealer: get closer to 21 without busting",
 "Больше 21 — пережог": "Over 21 — bust",
 "Больше фишек в конце — победа": "More discs at the end wins",
 "Бросай фишки в колонки и собери четыре в ряд раньше ИИ": "Drop discs into columns and line up four before the AI",
 "Быки и коровы — Игротека": "Bulls & Cows — Igroteka",
 "Быки, коровы": "Bulls & Cows",
 "Было показано": "Shown was",
 "Было показано:": "Shown was:",
 "В": "J",
 "В меню": "Menu",
 "ВЕРТОЛЁТ": "COPTER",
 "ВИСЕЛИЦА": "HANGMAN",
 "ВОЛНА": "WAVE",
 "ВРЕМЯ ВЫШЛО!": "TIME’S UP!",
 "ВСЕ ПАРЫ!": "ALL PAIRS!",
 "ВЫКЛЮЧИ СВЕТ": "LIGHTS OUT",
 "Ваш ход": "Your move",
 "Ваш ход — вы играете ✕": "Your move — you play ✕",
 "Ваш ход — вы чёрные ⚫": "Your move — you are black ⚫",
 "Ваш ход — кликните палочку, возьмёте её и все правее": "Your move — click a stick to take it and everything to its right",
 "Введи ставку": "Enter a bet",
 "Введи число по памяти": "Type the number from memory",
 "Вводи 4 цифры без повторов": "Enter 4 digits without repeats",
 "Веди шар мышью или пальцем.\nЗелёные шары меньше тебя — ешь их: очки и рост. Красные больше — они съедят тебя при касании.\nШар медленно тает сам по себе: без добычи долго не проживёшь. Съел слишком большой — конец.": "Steer the orb with the mouse or finger.\nGreen orbs are smaller than you — eat them: points and growth. Red ones are bigger — they’ll eat you on contact.\nThe orb slowly melts on its own: without prey you won’t last long. Swallowed by a much bigger one — game over.",
 "Верно!": "Correct!",
 "Верно! Уровень": "Correct! Level",
 "Вертолёт": "Copter",
 "Вертолёт — Игротека": "Copter — Igroteka",
 "Верхнее поле — флот ИИ (стреляй)": "Top grid — the AI fleet (fire away)",
 "Верхнее поле — флот ИИ: кликай по его клеткам, чтобы стрелять. Твой флот внизу, расставлен случайно.\nФлот: 4-палубный, две 3-палубных, две 2-палубных и два одиночных катера.\nПотопи весь флот ИИ раньше, чем он потопит твой. ИИ добивает раненые корабли — не подставляй одиночные клетки рядом.": "The top grid is the AI fleet: click its cells to fire. Your fleet is at the bottom, placed randomly.\nThe fleet: one 4-decker, two 3-deckers, two 2-deckers and two single boats.\nSink the whole AI fleet before it sinks yours. The AI finishes wounded ships — don’t expose lone cells nearby.",
 "Ветер:": "Wind:",
 "Ветер: ": "Wind: ",
 "Виселица": "Hangman",
 "Виселица — Игротека": "Hangman — Igroteka",
 "Внимательно читай задание сверху!": "Read the task at the top carefully!",
 "Волна": "Wave",
 "Волна ": "Wave ",
 "Волны": "Waves",
 "Врезался в препятствие": "Crashed into an obstacle",
 "Врезался в стену": "Crashed into the wall",
 "Врезался в стену пещеры": "Crashed into the cave wall",
 "Время": "Time",
 "Время вышло": "Time is up",
 "Время вышло!": "Time is up!",
 "Время:": "Time:",
 "Все 12 уровней пройдены!": "All 12 levels cleared!",
 "Все лампы погашены!": "All lights are out!",
 "Все мины разминированы": "All mines cleared",
 "Все мины разминированы!": "All mines cleared!",
 "Все мишени сбиты": "All targets down",
 "Все уровни пройдены! Последний — за": "All levels cleared! The last one —",
 "Всего": "Total",
 "Всего побед": "Total wins",
 "Вы": "You",
 "Вы взяли последнюю палочку!": "You took the last stick!",
 "Вы играете ✕": "You play ✕",
 "Вы победили! 🎉": "You won! 🎉",
 "Выбери СМЫСЛ слова:": "Pick the MEANING of the word:",
 "Выбери ЦВЕТ текста:": "Pick the COLOR of the text:",
 "Выбери клетку, затем цифру": "Pick a cell, then a digit",
 "Выбери пустую клетку, затем цифру 1–9 (кнопки внизу); ✕ — стереть.\nВ каждой строке, столбце и блоке 3×3 все цифры разные — конфликты сразу краснеют.\nУ каждой головоломки ровно одно решение. Победа — полное поле без конфликтов; рекорд — время решения.": "Pick an empty cell, then a digit 1–9 (buttons below); ✕ — erase.\nEvery row, column and 3×3 block must contain distinct digits — conflicts turn red immediately.\nEvery puzzle has exactly one solution. Winning is a full conflict-free board; best — your solving time.",
 "Выбери ставку": "Place a bet",
 "Выбери ставку (10/25/50). «Ещё» (H) — взять карту, «Хватит» (S) — остановиться.\nНабери ближе к 21, чем дилер, не пережав. 2–10 — по номиналу, картинки — по 10, туз — 1 или 11.\nДилер добирает до 17. Блэкджек (21 с двух карт) платит 3:2, равные суммы — пуш (возврат ставки).\nБанк кончился — получишь новый, но рекорд банка сохраняется.": "Choose a bet (10/25/50). “Hit” (H) — take a card, “Stand” (S) — stop.\nGet closer to 21 than the dealer without busting. 2–10 — face value, pictures — 10, ace — 1 or 11.\nThe dealer draws to 17. Blackjack (21 on two cards) pays 3:2, equal totals — a push (bet returned).\nIf the bank runs out you get a new one, but the best bank is kept.",
 "Выбирай ставку": "Choose a bet",
 "Выбирай цвет текста или смысл слова — задание меняется само. 45 секунд": "Pick the text color or the word meaning — the task switches on its own. 45 seconds",
 "Выключи свет": "Lights Out",
 "Выключи свет — Игротека": "Lights Out — Igroteka",
 "Высота": "Altitude",
 "Выстрелов до спуска: ": "Shots until drop: ",
 "ГОМОКУ": "GOMOKU",
 "Гомоку": "Gomoku",
 "Гомоку — Игротека": "Gomoku — Igroteka",
 "Готов?": "Ready?",
 "Готово!": "Done!",
 "Д": "Q",
 "ДИНО": "DINO",
 "ДУДЛ": "DOODLE",
 "Держи Пробел, клик или палец — вертолёт набирает высоту; отпусти — плавно снижается.\nПролетай через пещеру: проход постепенно сужается.\nКасание стены — конец. Счёт — пройденная дистанция: главное — ровный ритм нажатий.": "Hold Space, click or finger — the copter climbs; release — it sinks smoothly.\nFly through the cave: the passage gradually narrows.\nTouching a wall ends the run. Score is distance flown: an even rhythm of presses is what matters.",
 "Держи тягу и проведи винтокрылую машину через пещеру": "Hold thrust and guide the copter through the cave",
 "Держи тягу, чтобы подниматься, и отпускай, чтобы снижаться. Не касайся стен": "Hold thrust to climb, release to sink. Don’t touch the walls",
 "Дилер": "Dealer",
 "Дилер пережог — ты выиграл!": "Dealer busted — you win!",
 "Дилер сильнее": "The dealer is stronger",
 "Дилер — ": "Dealer — ",
 "Дино": "Dino",
 "Дино — Игротека": "Dino — Igroteka",
 "Дистанция": "Distance",
 "Длина": "Length",
 "Дождь из метеоритов: уворачивайся как можно дольше. Три жизни": "Meteor rain: dodge for as long as you can. Three lives",
 "Дудл": "Doodle",
 "Дудл — Игротека": "Doodle — Igroteka",
 "Дуэль артиллерии: угадай угол, силу и учти ветер. Кто первый попал — тот и молодец": "Artillery duel: find the angle, the power, and mind the wind. First to hit wins",
 "Дуэль с ракетками — обыграй ИИ до 7 очков": "Paddle duel — beat the AI to 7 points",
 "Ешь шары меньше себя и не попадись большим — и не таяй": "Eat orbs smaller than you, avoid bigger ones — and don’t melt",
 "Ешь шары меньше себя и не попадись большим. Шар медленно тает": "Eat orbs smaller than you, avoid bigger ones. Your orb slowly melts",
 "Ещё (H)": "Hit (H)",
 "Ещё матч": "Rematch",
 "Ещё не играли": "Not played yet",
 "Ещё партия": "Play again",
 "Ещё раз": "Once more",
 "Ещё ход!": "Extra turn!",
 "ЖЁЛТЫЙ": "YELLOW",
 "ЖМИ!": "WHACK!",
 "Жизни": "Lives",
 "ЗЕЛЁНЫЙ": "GREEN",
 "ЗМЕЙКА": "SNAKE",
 "Забей ИИ семь шайб — ракетка следует за пальцем": "Score seven past the AI — the paddle follows your finger",
 "Забей ИИ семь шайб — ракетка следует за пальцем ": "Score seven past the AI — the paddle follows your finger",
 "Загаданы 4 разные цифры. Бык — цифра на своём месте, корова — не на своём": "4 different digits are hidden. Bull — right place, cow — wrong place",
 "Зажатые фишки переворачиваются": "Sandwiched discs flip over",
 "Зажимай фишки ИИ, переворачивай их и захватывай доску": "Sandwich AI discs, flip them and take over the board",
 "Заново": "Restart",
 "Заново (R)": "Restart (R)",
 "Заполни поле 9×9: в строках, столбцах и блоках 3×3 — цифры 1–9 без повторов": "Fill the 9×9 grid: rows, columns and 3×3 blocks take digits 1–9 without repeats",
 "Запоминай и повторяй растущую последовательность нот": "Memorize and repeat the growing note sequence",
 "Запоминай последовательность нот и повторяй её": "Memorize the note sequence and repeat it",
 "Запоминай, где что лежит": "Remember where everything is",
 "Запомни число и введи его — с каждым уровнем длиннее": "Memorize the number and type it — longer every level",
 "Запомни число и введи его. С каждым уровнем — на цифру длиннее": "Memorize the number and type it. Each level adds one digit",
 "Запомни!": "Remember!",
 "Звук (M)": "Sound (M)",
 "Звук можно выключить в любой игре —": "Sound can be muted in any game —",
 "Здоровье кончилось": "Out of health",
 "Зелёные можно есть, красные опасны": "Green ones are edible, red ones are dangerous",
 "Зелёный — на месте · жёлтый — есть в слове · серый — нет": "Green — right spot · yellow — in the word · gray — absent",
 "Змейка": "Snake",
 "Змейка — Игротека": "Snake — Igroteka",
 "Зн/мин": "CPM",
 "Знаков в минуту (без ошибок)": "Characters per minute (no mistakes)",
 "Золотые кроты дороже": "Golden moles are worth more",
 "ИГРА ОКОНЧЕНА": "GAME OVER",
 "ИГРОТЕКА": "IGROTEKA",
 "ИДЕАЛЬНО!": "PERFECT!",
 "ИИ": "AI",
 "ИИ ВЫИГРАЛ": "AI WINS",
 "ИИ взял последнюю палочку": "The AI took the last stick",
 "ИИ выиграл": "AI won",
 "ИИ думает…": "AI is thinking…",
 "ИИ забил седьмую": "AI scored the seventh",
 "ИИ начинает…": "AI starts…",
 "ИИ непобедим — ничья тоже результат": "The AI is unbeatable — a draw is a result too",
 "ИИ победил": "AI won",
 "ИИ победил. Попробуйте ещё!": "AI won. Try again!",
 "ИИ пропустил ход — ваш снова": "AI passed — your move again",
 "ИИ собрал пять": "AI made five",
 "ИИ собрал четыре": "AI made four",
 "ИНВЕЙДЕРЫ": "INVADERS",
 "Играть →": "Play →",
 "Игрок": "Player",
 "Игротека": "Igroteka",
 "Игротека — 45 мини-игр": "Igroteka — 50 mini-games",
 "Игротека — 50 мини-игр": "Igroteka — 50 mini-games",
 "Идеальная укладка расширяет блок": "Perfect stacking widens the block",
 "Из": "of",
 "Инвейдеры": "Invaders",
 "Инвейдеры — Игротека": "Invaders — Igroteka",
 "К": "K",
 "КОД": "CODEBREAKER",
 "КОРАБЛЬ ПОТЕРЯН": "SHIP LOST",
 "КРАСНЫЙ": "RED",
 "КРЕСТИКИ": "TIC-TAC-TOE",
 "КРОТЫ": "WHACK-A-MOLE",
 "Каждые 8 выстрелов потолок опускается": "The ceiling drops every 8 shots",
 "Каждый клик переключает лампу и её соседей. Погаси все за минимум ходов": "Each click flips a lamp and its neighbors. Turn them all off in as few clicks as possible",
 "Каждый клик переключает плюс-фигуру. Погаси все лампы": "Each click flips a plus-shape. Turn every light off",
 "Касание трубы": "Hit a pipe",
 "Клавиатура на экране или физическая": "On-screen or physical keyboard",
 "Клавиатура, мышь и свайпы": "Keyboard, mouse and swipes",
 "Клавиши 1–4 или клик по кнопкам": "Keys 1–4 or click the buttons",
 "Классика": "Classics",
 "Классика 9×9 с генератором и единственным решением": "Classic 9×9 with a generator and a unique solution",
 "Классическая дуэль: обыграй ИИ со счётом 7:×": "Classic duel: beat the AI 7:×",
 "Клик": "Click",
 "Клик / тап / Пробел — сброс": "Click / tap / Space — drop",
 "Клик между точками — линия": "Click between dots — draw a line",
 "Клик по колонке — бросить фишку": "Click a column — drop a disc",
 "Клик по лампе переключает её и четырёх соседей крестом.\nПогаси все лампы. Поле всегда решаемо — генерируется обратными ходами.\nРекорд — минимальное число кликов. Если зашли в тупик — «Заново» перемешает новое поле.": "Clicking a lamp flips it and its four neighbors in a cross.\nTurn every lamp off. The board is always solvable — it’s generated by reverse clicks.\nBest — the fewest clicks. If you’re stuck, “Restart” shuffles a fresh board.",
 "Клик по мишени": "Click the target",
 "Клик по мишени — попадание": "Click a target — hit",
 "Клик по палочке берёт её и все правее в этом ряду": "Clicking a stick takes it and every stick to its right in that row",
 "Клик по палочке берёт её и все правее в этом ряду (ходить можно только в одном ряду).\nХоды чередуются с ИИ. Кто возьмёт ПОСЛЕДНЮЮ палочку — тот победил.\nИИ играет безошибочно (ним-сумма): выиграть можно, только передав ему сначала проигрышную позицию.": "Clicking a stick takes it and every stick to its right in that row (you may only move within one row).\nTurns alternate with the AI. Whoever takes the LAST stick wins.\nThe AI plays flawlessly (nim-sum): you can only win by handing it a losing position first.",
 "Клик по пустой клетке — поставить фишку": "Click an empty cell — place a stone",
 "Клик по пустой клетке — ставишь чёрную фишку. ИИ отвечает белой.\nПобеждает первый, собравший 5 своих фишек в ряд — по вертикали, горизонтали или диагонали.\nИИ ставит фишки рядом с твоими и перекрывает длинные линии — строй сразу несколько угроз.": "Click an empty cell — you place a black stone. The AI answers with white.\nWhoever lines up 5 of their stones first — vertically, horizontally or diagonally — wins.\nThe AI plays next to your stones and blocks long lines — build several threats at once.",
 "Клик по своей яме (нижний ряд) — камни раскладываются по одному против часовой стрелки; свой магазин пропускаешь, магазин ИИ — тоже.\nПоследний камень упал в твой магазин — ещё один ход подряд.\nПоследний камень упал в пустую свою яму — забираешь камни из ямы напротив.\nЯмы у кого-то опустели — второй забирает остаток. У кого больше в магазине — победа.": "Click one of your pits (bottom row) — stones are sown one by one counter-clockwise; your store is skipped, and the AI’s store too.\nIf the last stone drops into your own store — take another turn.\nIf the last stone drops into an empty pit of yours — you capture the stones from the opposite pit.\nWhen either side runs empty, the other collects the rest. Whoever holds more in their store wins.",
 "Клик по своей яме — посеять": "Click your pit — sow",
 "Клик по стержню — взять верхний диск, клик по другому стержню — перенести его туда.\nКласть можно только меньший диск на больший, по одному за ход.\nПеренеси всю башню на правый стержень. Минимум ходов — 31; рекорд считается по ходам.": "Click a rod to take the top disc, click another rod to drop it there.\nYou may only place a smaller disc on a bigger one, one disc per move.\nMove the whole tower to the right rod. The minimum is 31 moves; best is measured in moves.",
 "Клик — выбрать, клик по соседу — поменять": "Click to pick up, click a neighbor — move it",
 "Клик — выбрать, клик по соседу — поменять ": "Click to pick, click a neighbor — swap",
 "Клик — выбрать/перенести": "Click — pick up / drop",
 "Клик — начало раунда. Жди: как только фон станет зелёным — кликай немедленно.\n5 раундов, итог — среднее время в миллисекундах.\nКлик раньше зелёного — фальстарт, раунд придётся переигрывать. Рекорд — лучшее среднее.": "Click — the round starts. Wait: as soon as the background turns green — click immediately.\n5 rounds, the result is your average time in milliseconds.\nClicking before green is a false start — the round must be replayed. Best — the lowest average.",
 "Клик — переключить плюс-фигуру": "Click — flip the plus-shape",
 "Клик — старт/реакция": "Click — start / react",
 "Кликай между точками, чтобы ставить линии — по очереди с ИИ.\nЗамкнул четвёртую сторону квадрата — квадрат твой: +1 очко и ещё один ход подряд.\nИИ не подставляется: бери квадраты, как только они появляются, а свои «три стороны» прячь.\nВсе линии заняты — у кого больше квадратов, тот победил.": "Click between dots to draw lines — alternating with the AI.\nClose the fourth side of a box and it’s yours: +1 point and another turn in a row.\nThe AI doesn’t gift boxes: grab them the moment they appear, and hide your own “three-sided” ones.\nWhen every line is drawn, whoever holds more boxes wins.",
 "Кликай по карточкам, чтобы открыть. Ход = две открытые карточки.\nОдинаковые остаются открытыми, разные переворачиваются обратно.\nНайди все 8 пар. Рекорд — минимум ходов; таймер идёт параллельно.": "Click cards to flip them over. A move = two opened cards.\nMatching cards stay open, mismatched ones flip back.\nFind all 8 pairs. Best — the fewest moves; a timer runs alongside.",
 "Кликни для итогов": "Click for results",
 "Кликни для следующего раунда": "Click for the next round",
 "Кликни кристалл, затем соседний — они поменяются местами.\nТри и более одинаковых в линию исчезают: верхние падают, сверху сыпятся новые.\nКаскады (когда срабатывает само после падения) дают всё больше очков за кристалл.\n90 секунд — собери максимум.": "Click a crystal, then a neighboring one — they swap places.\nThree or more identical in a line vanish: the ones above fall, new ones pour in from the top.\nCascades (when matches trigger by themselves after a fall) score more per crystal.\n90 seconds — score as much as you can.",
 "Кликни по колонке — фишка упадёт в нижнюю свободную клетку.\nСобери четыре свои фишки подряд: по горизонтали, вертикали или диагонали — раньше ИИ.\nИИ просчитывает на несколько ходов вперёд и сразу блокирует три твоих в ряд — начинай с центральных колонок.": "Click a column — your disc falls into the lowest free cell.\nLine up four of your discs: horizontally, vertically or diagonally — before the AI does.\nThe AI looks several moves ahead and instantly blocks three-in-a-row — start from the central columns.",
 "Кликни по кроту!": "Whack the mole!",
 "Кликни фишку рядом с пустой клеткой — она сдвинется. Стрелки двигают фишки в направлении стрелки.\nСобери числа по порядку 1–15, пустая клетка — в правом нижнем углу.\nПеремешивание делается только законными ходами, так что поле всегда решаемо.\nРекорд — минимальное число ходов; время считается отдельно.": "Click a tile next to the empty cell — it slides over. Arrows push the tiles in the arrow’s direction.\nArrange the numbers 1–15 in order, with the empty cell in the bottom-right corner.\nShuffling only uses legal moves, so the board is always solvable.\nBest — the fewest moves; time is tracked separately.",
 "Кликни, когда фон станет зелёным": "Click when the background turns green",
 "Кликни, чтобы начать": "Click to start",
 "Кликни, чтобы попробовать снова": "Click to try again",
 "Кнопки загораются в определённом порядке и звучат нотами — запомни.\nПовтори последовательность кликами или клавишами 1–4.\nКаждый уровень добавляет ноту и ускоряет показ. Одна ошибка — конец. Рекорд — уровень.": "The buttons light up in a certain order and sound notes — memorize it.\nRepeat the sequence by clicking or with keys 1–4.\nEach level adds a note and speeds up the show. One mistake — game over. Best — level.",
 "Код": "Codebreaker",
 "Код взломан!": "Code cracked!",
 "Код — Игротека": "Codebreaker — Igroteka",
 "Комбо": "Combo",
 "Комбо растёт с серией верных ответов": "Combo grows with every correct answer",
 "Компьютер загадал 4 разные цифры от 0 до 9. Вводи варианты: 4 цифры без повторов.\n🐂 Бык — цифра угадана и стоит на своём месте. 🐄 Корова — цифра есть, но на другом месте.\nЦель — 4 быка. Все попытки с ответами видны в журнале — анализируй. Рекорд — минимум попыток.": "The computer picked 4 different digits from 0 to 9. Enter guesses: 4 digits, no repeats.\n🐂 Bull — the digit is guessed and stands in its place. 🐄 Cow — the digit is present but elsewhere.\nThe goal is 4 bulls. Every guess with its answer stays in the log — analyze it. Best — the fewest tries.",
 "Корабли": "Ships",
 "Корабль разбит метеоритом": "Ship smashed by a meteor",
 "Красное — конфликт": "Red — conflict",
 "Крестики": "Tic-tac-toe",
 "Крестики-нолики — Игротека": "Tic-tac-toe — Igroteka",
 "Кроты": "Whack-a-Mole",
 "Кроты появляются всё быстрее": "Moles pop up faster and faster",
 "Кроты — Игротека": "Whack-a-Mole — Igroteka",
 "Кто соберёт больше камней в свой магазин. Последний камень в магазин даёт ещё ход": "Collect more stones in your store. The last stone into the store grants another turn",
 "ЛКМ": "LMB",
 "ЛКМ — открыть клетку, ПКМ — флажок (на телефоне — долгое нажатие).\nПервый клик всегда безопасен: мины расставляются после него, рядом с первым открытием мин не будет.\nЦифра = число мин в 8 соседних клетках. Открытая цифра + двойной клик откроет соседей, если флажков вокруг ровно столько же.\nОткрой все клетки без мин — победа. Ошибочные флажки помечаются ❌ при взрыве.\nРекорд — лучшее время для каждой сложности.": "LMB — reveal a cell, RMB — flag (long press on mobile).\nThe first click is always safe: mines are placed after it, none near your first reveal.\nA digit = the number of mines in the 8 neighboring cells. An open digit + a double click reveals neighbors if the flags around match it exactly.\nReveal every safe cell — you win. Wrong flags are marked ❌ on explosion.\nBest — the fastest time for each difficulty.",
 "ЛУНА": "LUNAR LANDER",
 "Лавируй между машинами на растущей скорости": "Weave through cars at ever-growing speed",
 "Линии": "Lines",
 "Линия достигнута": "Reached the line",
 "Логика и настольные": "Logic & Board",
 "Ложный старт!": "False start!",
 "Луна": "Lunar Lander",
 "Луна — Игротека": "Lunar Lander — Igroteka",
 "Лучшее время": "Best time",
 "Лучшее среднее": "Best average",
 "Лучшее среднее:": "Best average:",
 "Любитель": "Amateur",
 "МАНКАЛА": "MANCALA",
 "МЕЛОДИЯ": "SIMON",
 "МЕТЕОРЫ": "METEORS",
 "МОРСКОЙ БОЙ": "BATTLESHIP",
 "Манкала": "Mancala",
 "Манкала — Игротека": "Mancala — Igroteka",
 "Математический спринт: чем длиннее серия — тем больше очков": "Math sprint: the longer the streak, the more points",
 "Матч до 7 очков": "Match to 7 points",
 "Матч до 7 шайб": "Match to 7 goals",
 "Матч твой!": "The match is yours!",
 "Мелодия": "Simon",
 "Мелодия — Игротека": "Simon — Igroteka",
 "Меньше попыток — лучше": "Fewer tries is better",
 "Меняй кристаллы местами, собирай линии и лови каскады": "Swap crystals, line them up and catch cascades",
 "Меняй соседние кристаллы местами и собирай линии из трёх и более": "Swap neighboring crystals and make lines of three or more",
 "Метеорит попал в корабль": "A meteor hit the ship",
 "Метеоритный дождь — уворачивайся как можно дольше": "Meteor shower — dodge for as long as you can",
 "Метеоры": "Meteors",
 "Метеоры — Игротека": "Meteors — Igroteka",
 "Метры": "Meters",
 "Мимо": "Miss",
 "Мимо площадки": "Missed the pad",
 "Мина взорвалась": "A mine exploded",
 "Мина взорвалась!": "A mine exploded!",
 "Минимум": "Minimum",
 "Минимум ходов": "Minimum moves",
 "Минимум ходов: ": "Minimum moves: ",
 "Минимум ходов: 31": "Minimum moves: 31",
 "Мины": "Mines",
 "Мишени появляются по одной — кликай по ним, всего 20 штук.\nПромах добавляет штраф +0,2 секунды к итогу.\nРекорд — минимальное общее время. Курсор — прицел: не суетись, но и не медли.": "Targets appear one at a time — click them, 20 in total.\nA miss adds a +0.2 second penalty to the total.\nBest — the lowest total time. The cursor is your scope: don’t rush, but don’t dawdle.",
 "Модуль опрокинулся": "The module tipped over",
 "Модуль разбит": "The module is wrecked",
 "Морской бой": "Battleship",
 "Морской бой — Игротека": "Battleship — Igroteka",
 "Мышь": "Mouse",
 "Мышь / палец / ← → — ракетка ": "Mouse / finger / ← → — paddle",
 "Мышь / палец / ↑↓ — ракетка": "Mouse / finger / ↑↓ — paddle",
 "Мышь / палец — веди шар": "Mouse / finger — steer the orb",
 "Мышь — прицел · клик — выстрел": "Mouse — aim · click — shoot",
 "Мышь — прицел, клик — выстрел. Стрелки — поворот, Пробел — выстрел.\nСобери 3+ пузыря одного цвета — они лопаются: +10 очков за каждый.\nПузыри, отвалившиеся от потолка, падают — +20 за каждый. Каждые 8 выстрелов потолок опускается на ряд.\nЛопнул весь потолок — новый уровень. Пузырь пересёк линию — конец.": "Mouse — aim, click — shoot. Arrows — rotate, Space — shoot.\nMatch 3+ bubbles of one color — they pop: +10 points each.\nBubbles detached from the ceiling fall — +20 each. Every 8 shots the ceiling drops one row.\nClear the whole ceiling — a new level. A bubble crossing the line ends the run.",
 "Мышь, палец или ← → — корабль внизу экрана.": "Mouse, finger or ← → — the ship at the bottom.",
 "Мышь, палец или ← → — корабль внизу экрана.\nУворачивайся от метеоритов: очки капают за время полёта, +5 за каждый улетевший мимо камень.\nТри жизни, после попадания — короткое мигание-неуязвимость. Чем дольше живёшь, тем гуще дождь и крупнее камни.": "Mouse, finger or ← → — the ship at the bottom of the screen.\nDodge the meteorites: points tick up while you fly, +5 for every rock that flies past.\nThree lives; after a hit you get a brief blink of invincibility. The longer you live, the thicker the rain and the bigger the rocks.",
 "Мышь, палец или ← → — платформа. Пробел или клик — запуск шара.\nРазбей все блоки: яркие держат два удара. Шар упал — минус жизнь (всего три).\nБонусы: W — шире платформа, S — медленный шар, M — мультишар (до 6 шаров).\nОчистил поле — новый уровень с другой раскладкой. Шар слегка ускоряется с каждым отбиванием.": "Mouse, finger or ← → — the paddle. Space or click — launch the ball.\nSmash every brick: bright ones take two hits. Lose the ball — lose a life (three in total).\nPower-ups: W — wider paddle, S — slow ball, M — multiball (up to 6 balls).\nClear the field — a new level with a fresh layout. The ball speeds up slightly with every bounce.",
 "Мышь, палец или ← → — твоя ракетка в нижней половине стола.\nЗабей 7 шайб в верхние ворота раньше, чем ИИ забьёт тебе.\nШайба ускоряется от ударов и слегка тормозит о воздух. ИИ играет аккуратно — выигрывай за счёт скорости.": "Mouse, finger or ← → — your paddle in the bottom half of the table.\nScore 7 goals into the top net before the AI scores into yours.\nThe puck speeds up on hits and slightly brakes on air. The AI plays carefully — win with speed.",
 "Мышь, ↑↓ (W/S) или палец — твоя ракетка слева.\nМатч до 7 очков. Мяч ускоряется с каждым отбиванием.\nУгол отскока зависит от точки удара: края ракетки отбивают острее.\nИИ следит за мячом, но его скорость ограничена — выигрывай позицию заранее.": "Mouse, ↑↓ (W/S) or finger — that’s your paddle on the left.\nMatch to 7 points. The ball speeds up with every hit.\nThe bounce angle depends on where it strikes: the paddle edges send it at sharper angles.\nThe AI follows the ball, but its speed is limited — win the position early.",
 "Мягкая посадка! Бонус": "Soft landing! Bonus",
 "НИМ": "NIM",
 "НИЧЬЯ": "DRAW",
 "На несколько секунд показывается число — запомни и введи его в поле.\nКаждый верный ответ добавляет одну цифру к следующему числу.\n3 жизни: третья ошибка — конец. Рекорд — достигнутый уровень (длина числа).": "A number is shown for a few seconds — memorize it and type it into the field.\nEvery correct answer adds one more digit to the next number.\n3 lives: the third mistake ends the run. Best — the level reached (the number’s length).",
 "Набери ближе к 21, чем дилер, и не пережги. Стартовый банк: 100": "Get closer to 21 than the dealer without busting. Starting bank: 100",
 "Набирай текст быстро и без ошибок. 60 секунд на всё": "Type fast and clean. 60 seconds in total",
 "Набирай фразы быстро и без ошибок — знаков в минуту": "Type phrases fast and clean — characters per minute",
 "Нажми «Играть» и слушай": "Press “Play” and listen",
 "Найди все пары одинаковых карточек, запоминая позиции": "Find every matching pair, memorizing positions",
 "Найди пару — Игротека": "Memory — Igroteka",
 "Например: 0123": "E.g. 0123",
 "Не угадали. Слово:": "No luck. The word:",
 "Нет линии — возврат": "No box — turn passes",
 "Нет ходов — вы пропускаете": "No moves — you pass",
 "Нижнее — твой флот": "Bottom — your fleet",
 "Ним": "Nim",
 "Ним — Игротека": "Nim — Igroteka",
 "Ничьи": "Draws",
 "Ничья — ИИ непобедим, но и вы непобедимы": "Draw — the AI is unbeatable, but so are you",
 "Ничья — поле заполнено": "Draw — the board is full",
 "Ничья!": "Draw!",
 "Ничья:": "Draw:",
 "Новая игра": "New game",
 "Новичок": "Novice",
 "Ноты падают по четырём дорожкам — жми D, F, J, K или тапай по дорожке, когда нота на линии.\nЧем точнее попадание и длиннее серия (комбо), тем больше очков за ноту.\nПропущенная нота отнимает здоровье. Здоровье на нуле — игра окончена.": "Notes fall down four lanes — press D, F, J, K or tap the lane when a note reaches the line.\nThe more precise the hit and the longer your streak (combo), the more points per note.\nA missed note costs health. At zero health the game ends.",
 "Ноты падают по четырём дорожкам — лови их на линии. Промахи отнимают здоровье": "Notes fall down four lanes — catch them on the line. Misses drain health",
 "Ноты падают по четырём дорожкам — лови на линии D F J K": "Notes fall down four lanes — catch them on the D F J K line",
 "Нужно ровно 4 цифры": "Exactly 4 digits required",
 "ОК": "OK",
 "ОЧКО": "BLACKJACK",
 "Обгоняй поток на трассе: три полосы, скорость растёт сама": "Overtake traffic: three lanes, speed rises on its own",
 "Осталось": "Left",
 "Отбивай волны пришельцев, пока они не приземлились": "Fight off alien waves before they land",
 "Отбивай волны пришельцев. Чем меньше их остаётся — тем быстрее они двигаются": "Fight off alien waves. The fewer remain, the faster they move",
 "Открывай по две карточки": "Open two cards at a time",
 "Открывай поле и разминируй все мины на время": "Clear the field and defuse every mine against the clock",
 "Открыты все пары!": "All pairs found!",
 "Открыть": "Reveal",
 "Открыть все": "Reveal all",
 "Отмена (Z)": "Undo (Z)",
 "Отменить ход (Z)": "Undo move (Z)",
 "Очки": "Points",
 "Очко": "Blackjack",
 "Очко — Игротека": "Blackjack — Igroteka",
 "Ошибка! Попробуй ещё раз": "Wrong! Try again",
 "Ошибки снижают точность": "Mistakes hurt accuracy",
 "Ошибок:": "Mistakes:",
 "ПАУЗА": "PAUSED",
 "ПЕЧАТЬ": "TYPING",
 "ПКМ": "RMB",
 "ПОБЕДА": "VICTORY",
 "ПОБЕДА!": "YOU WIN!",
 "ПОЖИРАТЕЛЬ": "ORBS",
 "ПОНГ": "PONG",
 "ПОРАЖЕНИЕ": "DEFEAT",
 "ПОТОК": "FLOW",
 "ПРАВИЛА": "RULES",
 "ПРОБКА": "TRAFFIC",
 "ПУЗЫРИ": "BUBBLES",
 "ПУШКА": "ARTILLERY",
 "ПЯТНАШКИ": "15 PUZZLE",
 "Падение": "Fell down",
 "Палитра внизу · 10 попыток": "Palette below · 10 tries",
 "Пара": "Memory",
 "Пары": "Pairs",
 "Пережог! Ставка проиграна": "Bust! Bet lost",
 "Перемешать": "Shuffle",
 "Перемешивание…": "Shuffling…",
 "Перенеси башню дисков на правый стержень за минимум ходов": "Move the tower to the right rod in as few moves as possible",
 "Перенеси башню на правый стержень. Класть можно только меньший диск на больший": "Move the tower to the right rod. Only a smaller disc may go onto a bigger one",
 "Пересёк линию": "Crossed the line",
 "Персонаж сам отскакивает от платформ. ← → или тап по половинам экрана — движение вбок; края экрана связаны: ушёл влево — выехал справа.\nПоднимайся как можно выше — счёт равен высоте. Жёлтые платформы двигаются.\nУпал ниже экрана — конец. Планируй прыжки: после отскока важно оказаться над следующей платформой.": "The character bounces off platforms by itself. ← → or tap the screen halves — move sideways; the edges are linked: leave left, reappear right.\nClimb as high as you can — your score equals your height. Yellow platforms move.\nFall below the screen — game over. Plan your jumps: after a bounce you need to land above the next platform.",
 "Печатай здесь…": "Type here…",
 "Печатай показанный текст в поле: фразы идут одна за другой, всего 60 секунд.\nСчёт — знаки в минуту БЕЗ ошибок; отдельно считается точность в процентах.\nОшибочная буква подчёркивается, но не блокирует дальнейший набор — исправляться можно на ходу.": "Type the shown text into the field: phrases follow one another, 60 seconds in total.\nYour score is characters per minute WITHOUT mistakes; accuracy is tracked separately as a percentage.\nA wrong letter is underlined but doesn’t block further typing — you can fix it on the go.",
 "Печать": "Typing",
 "Печать — Игротека": "Typing — Igroteka",
 "Пилотируй корабль с физикой инерции и разбивай камни": "Pilot a ship with inertia physics and smash rocks",
 "Пилотируй корабль, разбивай камни, не дай себя настигнуть": "Pilot the ship, smash rocks, don’t let them overtake you",
 "Плитка 2048 собрана. Дальше — только сильнее": "Tile 2048 made. It only gets tougher from here",
 "Побед": "Wins",
 "Побед в дуэлях": "Duel wins",
 "Побед в дуэлях:": "Duel wins:",
 "Побед всего:": "Total wins:",
 "Побед над ИИ": "Wins vs AI",
 "Побед над ИИ:": "Wins vs AI:",
 "Победа над ИИ": "Win vs AI",
 "Победа над ИИ!": "You beat the AI!",
 "Победа!": "You win!",
 "Победи непобедимый ИИ — или сыграй с ним вничью": "Beat the unbeatable AI — or hold it to a draw",
 "Победы": "Wins",
 "Поворот": "Rotate",
 "Пожиратель": "Orbs",
 "Пожиратель — Игротека": "Orbs — Igroteka",
 "Поле должно быть заполнено целиком": "The board must be filled completely",
 "Поле заполнено целиком — невероятно!": "The board is completely full — incredible!",
 "Поле заполнилось": "The board filled up",
 "Понг": "Pong",
 "Понг — Игротека": "Pong — Igroteka",
 "Понятно": "Got it",
 "Попадание!": "Hit!",
 "Попытка": "Try",
 "Попытки": "Tries",
 "Попытки кончились": "Out of tries",
 "Портал": "Portal",
 "Посади лунный модуль мягко, ровно и на площадку": "Land the lunar module softly, straight, on the pad",
 "Посади модуль на площадку: медленно и вертикально. Топливо ограничено": "Land the module on the pad: slow and vertical. Fuel is limited",
 "Посадки": "Landings",
 "Последний уровень пройден!": "Last level cleared!",
 "Последовательность нарушена": "The sequence is broken",
 "Поток": "Flow",
 "Поток — Игротека": "Flow — Igroteka",
 "Потопи все корабли ИИ. Кликай по его полю, стреляй по клеткам": "Sink all AI ships. Click its grid to fire at cells",
 "Потопи флот ИИ раньше, чем он потопит твой": "Sink the AI fleet before it sinks yours",
 "Правила": "Rules",
 "Приготовься…": "Get ready…",
 "Пришельцы прорвались": "The aliens broke through",
 "Пробел": "Space",
 "Пробел / клик / тап — взмах крыльев": "Space / click / tap — flap",
 "Пробел / клик / тап — держать тягу": "Space / click / tap — hold thrust",
 "Пробел или клик — запуск": "Space or click — launch",
 "Пробел или клик — запуск шара": "Space or click — launch the ball",
 "Пробел — заново": "Space — restart",
 "Пробел — продолжить · Esc — в меню": "Space — resume · Esc — menu",
 "Пробел — прыжок · ↓ — пригнуться": "Space — jump · ↓ — duck",
 "Пробел, ↑, клик или тап — взмах крыльев: птичка подскакивает. Без взмахов она падает.\nПролетай в щели между трубами — +1 очко за каждую.\nКасание трубы или земли — конец. Вся игра — в ритме взмахов.": "Space, ↑, click or tap — flap: the bird hops up. Without flapping it falls.\nFly through the gaps between pipes — +1 point for each.\nTouching a pipe or the ground ends the run. The whole game is the rhythm of your flaps.",
 "Пробел/↑/тап — прыжок, ↓ или свайп вниз — пригнуться.\nПерепрыгивай кактусы (бывают группами), пригибайся под низкими птицами.\nСкорость и счёт растут сами собой. Одно столкновение — конец.\nСчёт — это дистанция: держись как можно дольше.": "Space/↑/tap — jump, ↓ or swipe down — duck.\nLeap over cacti (sometimes in groups), duck under low birds.\nSpeed and score grow on their own. A single collision ends the run.\nYour score is the distance — hold on as long as you can.",
 "Пробка": "Traffic",
 "Пробка — Игротека": "Traffic — Igroteka",
 "Проверить": "Check",
 "Продолжить": "Resume",
 "Пройди все 6 уровней. Рекорд — ходы на последнем уровне": "Clear all 6 levels. Best — moves on the last level",
 "Пролетай между трубами — одно касание, один взмах": "Fly between the pipes — one tap, one flap",
 "Промах добавляет штраф": "A miss adds a penalty",
 "Промахи": "Misses",
 "Промахи добавляют штраф 0,2 с": "Misses add a 0.2 s penalty",
 "Профи": "Pro",
 "Проходи сквозь стены": "Pass through walls",
 "Прошлый": "Prev",
 "Прыгай по платформам всё выше — не падай вниз": "Bounce ever higher — don’t fall down",
 "Прыгай по платформам как можно выше. Падение внизу — конец": "Bounce as high as you can. Falling below ends the run",
 "Прямое попадание!": "Direct hit!",
 "Пузыри": "Bubbles",
 "Пузыри — Игротека": "Bubbles — Igroteka",
 "Пуш — ставка возвращается": "Push — bet returned",
 "Пушка": "Artillery",
 "Пушка — Игротека": "Artillery — Igroteka",
 "Пятнашки": "15 Puzzle",
 "Пятнашки — Игротека": "15 Puzzle — Igroteka",
 "Пять в ряд!": "Five in a row!",
 "Пять фишек в ряд на доске 15×15 против хитрого ИИ": "Five in a row on a 15×15 board against a cunning AI",
 "РЕАКЦИЯ": "REACTION",
 "РЕВЕРСИ": "REVERSI",
 "РИТМ": "RHYTHM",
 "Разбей все блоки — ловь бонусы, не упусти шар": "Smash every brick — catch power-ups, don’t lose the ball",
 "Разбивай блоки шаром, ловь бонусы и держи удар": "Smash bricks with the ball, catch power-ups, keep the streak",
 "Рано кликнул — раунд сгорает": "Clicked too early — the round is forfeit",
 "Расставь фишки по порядку за минимум ходов": "Sort the tiles in order in as few moves as possible",
 "Растворился…": "You melted away…",
 "Раунд": "Round",
 "Раунд ": "Round ",
 "Реакция": "Reaction",
 "Реакция и навыки": "Reaction & Skills",
 "Реакция — Игротeca": "Reaction — Igroteka",
 "Реакция — Игротека": "Reaction — Igroteka",
 "Реверси": "Reversi",
 "Реверси — Игротека": "Reversi — Igroteka",
 "Режим флажков": "Flag mode",
 "Результаты:": "Results:",
 "Рекорд": "Best",
 "Рекорд банка": "Best bank",
 "Рекорд:": "Best:",
 "Рекорд: ": "Best: ",
 "Реши как можно больше примеров за 60 секунд. Серия верных даёт комбо": "Solve as many problems as you can in 60 seconds. Streaks build combo",
 "Ритм": "Rhythm",
 "Ритм — Игротека": "Rhythm — Igroteka",
 "Роняй блоки точно друг на друга — высота решает": "Drop blocks precisely on each other — height wins",
 "С каждым уровнем мелодия длиннее и быстрее": "Each level the melody gets longer and faster",
 "САПЁР": "MINESWEEPER",
 "СБОЙ!": "WRONG!",
 "СБРОС": "DROP",
 "СИНИЙ": "BLUE",
 "СЛОВО": "WORDLY",
 "СОБРАНО!": "SOLVED!",
 "СОЕДИНИ 4": "CONNECT 4",
 "СОКОБАН": "SOKOBAN",
 "СТОЛКНОВЕНИЕ!": "CRASH!",
 "СТРУП": "STROOP",
 "СУДОКУ": "SUDOKU",
 "СЧЁТ": "SCORE",
 "Сапёр": "Minesweeper",
 "Сапёр — Игротека": "Minesweeper — Igroteka",
 "Сбой!": "Wrong!",
 "Сброс": "Drop",
 "Свайпы на телефоне · Пробел — пауза": "Swipes on mobile · Space — pause",
 "Сей камни по кругу и собери больше всех в свой магазин": "Sow stones around the board and collect the most in your store",
 "Секретный код — 4 цвета из шести, повторы возможны.\nВыбирай цвета в палитре и заполняй ряд, затем «Проверить».\n🟢 — цвет угадан и стоит на своём месте, 🟡 — цвет есть, но в другой клетке.\n10 попыток. Рекорд — минимальное число попыток.": "The secret code is 4 colors out of six, repeats possible.\nPick colors from the palette to fill the row, then press “Check”.\n🟢 — right color in the right spot, 🟡 — the color is present but elsewhere.\n10 tries. Best — the fewest tries.",
 "Скорость ≤ 55 по вертикали, ≤ 30 по горизонтали": "Speed ≤ 55 vertical, ≤ 30 horizontal",
 "Следующая": "Next",
 "Следующий": "Next",
 "Слишком боковой снос": "Too much sideways drift",
 "Слишком быстро": "Too fast",
 "Слишком быстро:": "Too fast:",
 "Слова": "Words",
 "Слово": "Wordly",
 "Слово было:": "The word was:",
 "Слово — Игротека": "Wordly — Igroteka",
 "Слово:": "Word:",
 "Слушай…": "Listen…",
 "Сменить поле": "New board",
 "Собери пять фишек в ряд по вертикали, горизонтали или диагонали": "Line up five stones vertically, horizontally or diagonally",
 "Собирай линии из падающих фигур": "Stack falling pieces, clear lines",
 "Собирай яблоки, лови золотые бонусы и не укуси себя": "Eat apples, grab golden bonuses — don’t bite yourself",
 "Собирай яблоки, лови золотые — и не укуси себя": "Eat apples, catch golden ones — don’t bite yourself",
 "Собрано!": "Solved!",
 "Соедини 4": "Connect 4",
 "Соедини 4 — Игротека": "Connect 4 — Igroteka",
 "Соедини пары цветных точек, заполнив всё поле": "Connect pairs of colored dots, filling the whole board",
 "Соединяй плитки с одинаковыми числами до 2048": "Merge tiles with the same numbers up to 2048",
 "Соединяй точки линиями. Замкнул квадрат — очко и ещё один ход": "Connect dots with lines. Close a box — a point and an extra turn",
 "Сокобан": "Sokoban",
 "Сокобан — Игротека": "Sokoban — Igroteka",
 "Среднее": "Average",
 "Средний": "Average",
 "Средняя реакция:": "Average reaction:",
 "Ставки": "Bets",
 "Ставь линии, замыкай квадраты — очко и ещё один ход": "Draw lines, close boxes — a point and an extra turn",
 "Ставьте фишку так, чтобы зажать фишки ИИ между своими": "Place a disc so the AI’s discs end up sandwiched between yours",
 "Стакан переполнился": "The well overflowed",
 "Старт": "Start",
 "Стены смертельны": "Walls are deadly",
 "Столкновение": "Collision",
 "Столкновение с астероидом": "Hit by an asteroid",
 "Столкновение со стеной": "Crashed into the wall",
 "Столкновение!": "Collision!",
 "Стрелка над пушками показывает силу ветра": "The arrow above the cannons shows the wind strength",
 "Стрелки/WASD или свайпы — сдвиг всех плиток разом.\nПлитки с одинаковыми числами сливаются в удвоенную. За каждое слияние — очки, равные новому числу.\nZ или «Отменить» — откат хода (до 8 шагов назад).\nСобери плитку 2048 — победа, после которой можно продолжить.\nХодов нет — игра окончена. Рекорд — максимальный счёт.": "Arrows/WASD or swipes — slide all tiles at once.\nTiles with equal numbers merge into a doubled one. Every merge scores points equal to the new number.\nZ or “Undo” — take a move back (up to 8 steps).\nMake the 2048 tile — you win, and may keep going.\nNo moves left — game over. Best is your top score.",
 "Стрелки/WASD — движение": "Arrows/WASD — move",
 "Стрелки/WASD — движение, на телефоне — свайпы.\nТолкай ящики 📦 на жёлтые цели. Толкать можно только по одному и только от себя — тянуть нельзя, ящик у стены не повернуть.\nZ — отмена хода (можно много раз), R — уровень заново.\nПройди все 6 уровней; рекорд — ходы на последнем уровне.": "Arrows/WASD — move, swipes on mobile.\nPush the crates 📦 onto the yellow targets. You can only push one crate at a time, straight ahead — no pulling, a crate against a wall can’t be turned.\nZ — undo a move (as many times as you like), R — restart the level.\nClear all 6 levels; best — moves on the last level.",
 "Стрелки/WASD — повороты, на телефоне — свайпы. Пробел — пауза.\nСобирай яблоки: 10 очков × комбо. Комбо растёт, если есть яблоки чаще, чем раз в 3,5 секунды (до ×8).\nКаждое 4-е яблоко приносит золотую звезду: +50 очков и +2 к длине, но она живёт 8 секунд — успей!\nКаждые 5 яблок — новый уровень и ускорение.\nРежимы: Классика — стены смертельны; Портал — проходишь сквозь стены; Аркада — каждое 3-е яблоко появляется камень (сначала мигает предупреждением).\nУкусил себя или врезался — конец. Рекорд — свой для каждого режима.": "Arrows/WASD — steering, swipes on mobile. Space — pause.\nEat apples: 10 points × combo. The combo grows if you eat apples more often than every 3.5 seconds (up to ×8).\nEvery 4th apple brings a golden star: +50 points and +2 length, but it lasts 8 seconds — hurry!\nEvery 5 apples — a new level and more speed.\nModes: Classic — walls kill; Portal — you pass through walls; Arcade — every 3rd apple spawns a rock (it blinks a warning first).\nBite yourself or crash — game over. Best is kept per mode.",
 "Стреляй шаром и лопай группы из трёх и более": "Shoot and pop groups of three or more",
 "Стреляй шаром, собирай группы из трёх и лопай": "Shoot a bubble, match groups of three and pop them",
 "Струп": "Stroop",
 "Струп — Игротека": "Stroop — Igroteka",
 "Судоку": "Sudoku",
 "Судоку решено!": "Sudoku solved!",
 "Судоку — Игротека": "Sudoku — Igroteka",
 "Счёт": "Score",
 "Счёт сессии": "Session score",
 "Счёт сессии: вы": "Session: you",
 "Счёт — Игротека": "Math Sprint — Igroteka",
 "Счёт — Игротека ": "Math Sprint — Igroteka",
 "Счёт: ⚫": "Score: ⚫",
 "Т": "A",
 "ТЕТРИС": "TETRIS",
 "ТЕТРИС! +": "TETRIS! +",
 "ТОЧКИ": "DOTS & BOXES",
 "ТРИ-В-РЯД": "MATCH 3",
 "Тап по дорожке на телефоне": "Tap a lane on mobile",
 "Тап по половинам экрана": "Tap screen halves",
 "Тап по половинам экрана ": "Tap screen halves ",
 "Твой выстрел": "Your shot",
 "Твой флот": "Your fleet",
 "Твой флот потоплен": "Your fleet is sunk",
 "Твой ход": "Your move",
 "Твой ход — ": "Your move — ",
 "Твой ход — повтори (": "Your turn — repeat (",
 "Тебя подбили": "You were hit",
 "Тебя съел шар побольше": "A bigger orb ate you",
 "Текст печатается в поле ниже": "The text is typed into the field below",
 "Тетрис": "Tetris",
 "Тетрис — Игротека": "Tetris — Igroteka",
 "Толкай ящики на цели. Ящик можно только толкать — не тяни в тупик!": "Push crates onto targets. Crates can only be pushed — don’t drag them into a corner!",
 "Толкай ящики на цели: 6 уровней, отмена хода": "Push crates onto targets: 6 levels, undo",
 "Только существительные в единственном числе": "Singular nouns only",
 "Точки": "Dots & Boxes",
 "Точки — Игротека": "Dots & Boxes — Igroteka",
 "Точность": "Accuracy",
 "Три-в-ряд": "Match 3",
 "Три-в-ряд — Игротека": "Match 3 — Igroteka",
 "Ты": "You",
 "Ты ближе к 21 — победа!": "You are closer to 21 — you win!",
 "Ты выиграл": "You won",
 "Ты победил!": "You won!",
 "Ты проиграл": "You lost",
 "Ты —": "You —",
 "Ты — дилер": "You — dealer",
 "Ты — игрок": "You — player",
 "Ты — чёрные. Точки на доске показывают, куда можно ходить: фишки ИИ, зажатые между твоими по любой линии, перевернутся.\nЕсли ходов нет — ход пропускается автоматически.\nУглы не переворачиваются никогда — самые ценные клетки.\nКогда ходить не может никто — подсчёт: у кого больше фишек, тот победил.": "You are black. Dots on the board show legal moves: AI discs sandwiched between yours on any line will flip.\nWith no legal moves your turn is skipped automatically.\nCorners never flip — they are the most valuable cells.\nWhen nobody can move, the count decides: whoever holds more discs wins.",
 "Ты — ✕, ИИ — ◯. Клик по клетке или клавиши 1–9.\nИИ играет идеально (полный перебор): выиграть у него нельзя, ничья — отличный результат.\nПервый ход чередуется каждую партию. Счёт сессии + общее число побед сохраняется.": "You are ✕, the AI is ◯. Click a cell or press keys 1–9.\nThe AI plays perfectly (full search): you cannot beat it, a draw is a great result.\nThe first move alternates every game. The session score and total wins are saved.",
 "Тяни от точки её цвета — за курсором потянется линия. Соедини две одинаковые точки.\nЛинии не пересекаются; клик по линии стирает её. Уровень решён, когда поле заполнено целиком.\n12 уровней: от 5×5 до 7×7. Рекорд — максимальный уровень за партию.": "Drag from a dot — a line of its color follows the cursor. Connect the two matching dots.\nLines don’t cross and don’t pass through other dots. A level is solved when the board is completely filled.\n12 levels: from 5×5 to 7×7. Best — the highest level reached in one run.",
 "Тяни от точки к паре · линии не пересекаются": "Drag from a dot to its pair · lines don’t cross",
 "УПАЛ!": "CRASHED!",
 "УРОВЕНЬ": "LEVEL",
 "Уворачивайся от камней": "Dodge the rocks",
 "Угадай 4 цифры: бык — на месте, корова — есть в числе": "Guess 4 digits: bull — right place, cow — present",
 "Угадай комбинацию из 4 цветов за минимум попыток": "Crack the 4-color code in as few tries as possible",
 "Угадай русское слово, открывая буквы: экранная клавиатура или физическая (раскладка не важна).\nКаждая ошибка дорисовывает часть виселицы. 7 ошибок — поражение, слово покажут.\nПобеды копятся в рекорде. Начни с гласных — они чаще встречаются.": "Guess the word by opening letters: on-screen keyboard or a physical one (layout doesn’t matter).\nEach mistake draws another part of the gallows. 7 mistakes — you lose, the word is revealed.\nWins stack up in your record. Start with vowels — they appear more often.",
 "Угадай слово из 5 букв за 6 попыток": "Guess the 5-letter word in 6 tries",
 "Угадай слово из 5 букв за 6 попыток — как в Wordle": "Guess the 5-letter word in 6 tries — like Wordle",
 "Угадай слово из 5 букв за 6 попыток. Только существительные из словаря (в единственном числе).\nПосле попытки буквы красятся: зелёный — на своём месте, жёлтый — есть в слове, но не здесь, серый — нет в слове.\nКлавиатура снизу повторяет подсказки. Слова без повторов информативнее для первого хода.": "Guess the 5-letter word in 6 tries. Only nouns from the dictionary (singular).\nAfter a guess the letters are colored: green — right spot, yellow — in the word but elsewhere, gray — not in the word.\nThe keyboard below repeats the hints. Words without repeated letters carry more information for the first try.",
 "Угадай слово по буквам, пока не кончились попытки": "Guess the word letter by letter before attempts run out",
 "Угадай слово по буквам. На ошибки — 7 попыток": "Guess the word letter by letter. You have 7 tries",
 "Угол": "Angle",
 "Удержание": "Hold",
 "Удержать": "Hold",
 "Укладывай падающие фигуры и собирай линии": "Stack falling pieces and clear lines",
 "Укусил себя за хвост": "Bit your own tail",
 "Упал на землю": "Fell to the ground",
 "Упал с высоты": "Fell from a height",
 "Уровень": "Level",
 "Уровень ": "Level ",
 "Уровень пройден": "Level cleared",
 "Уровень пройден!": "Level cleared!",
 "Финиш": "Finish",
 "Флот ИИ": "AI fleet",
 "Флот ИИ уничтожен!": "The AI fleet is destroyed!",
 "Флот отступил": "The fleet retreated",
 "Фраза набрана!": "Phrase typed!",
 "ХАНОЙ": "TOWER OF HANOI",
 "ХОДОВ НЕТ": "NO MOVES",
 "Ханой": "Tower of Hanoi",
 "Ханой — Игротека": "Tower of Hanoi — Igroteka",
 "Хватит (S)": "Stand (S)",
 "Ход": "Move",
 "Ход ИИ…": "AI’s move…",
 "Ходи по часовой (вверх → вправо → вниз → влево)": "Move clockwise (up → right → down → left)",
 "Ходы": "Moves",
 "Ходят по очереди с ИИ": "Turns alternate with the AI",
 "ЦЕПОЧКА": "NUMBER SPAN",
 "Цвет или смысл? Мозг путается — победи его за 45 секунд": "Color or meaning? Your brain gets confused — beat it in 45 seconds",
 "Цель — минимальное число ходов": "Goal — as few moves as possible",
 "Цепочка": "Number Span",
 "Цепочка — Игротека": "Number Span — Igroteka",
 "Цифры не должны повторяться": "Digits must not repeat",
 "ЧИСТО!": "CLEAR!",
 "Четыре в ряд!": "Four in a row!",
 "Число": "Number",
 "Число показывается несколько секунд": "The number is shown for a few seconds",
 "Читай задание сверху: «Выбери ЦВЕТ текста» или «Выбери СМЫСЛ слова».\nСлово «КРАСНЫЙ», написанное синим: цвет — синий, смысл — красный. Мозг будет путаться — в этом и игра.\n45 секунд; верный ответ +1, ошибка −1. Клавиши 1–4 равны цветным кнопкам.": "Read the task at the top: “Pick the COLOR of the text” or “Pick the MEANING of the word”.\nThe word “RED” written in blue: the color is blue, the meaning is red. Your brain will tangle — that’s the game.\n45 seconds; a correct answer +1, a mistake −1. Keys 1–4 equal the color buttons.",
 "Шар улетел": "The ball is gone",
 "Шары закончились": "Out of balls",
 "Яблок": "Apples",
 "Ящик на цели": "Crate on target",
 "аркада · рост": "arcade · growth",
 "банк": "bank",
 "бонусы · мультишар": "power-ups · multiball",
 "было показано": "was shown",
 "взмах": "flap",
 "волны": "waves",
 "время:": "time:",
 "головоломка": "puzzle",
 "двигать в направлении стрелки": "push toward the arrow",
 "движение": "move",
 "долгое нажатие — флажок": "long press — flag",
 "древняя игра": "ancient game",
 "дуэль": "duel",
 "есть, но не здесь": "present, wrong place",
 "ещё два шара": "two more balls",
 "з/м": "cpm",
 "заново": "restart",
 "запуск": "launch",
 "звук": "sound",
 "игрок": "player",
 "идеальный ИИ": "perfect AI",
 "из": "of",
 "карты · банк": "cards · bank",
 "классика": "classic",
 "км/ч": "km/h",
 "когнитивный": "cognitive",
 "логика": "logic",
 "логика чисел": "number logic",
 "м": "m",
 "медленней шар": "slower ball",
 "миллисекунды": "milliseconds",
 "мин)": "min)",
 "мс": "ms",
 "мультишар": "multiball",
 "на время": "timed",
 "на месте": "right spot",
 "на телефоне — палец": "on mobile — finger",
 "на телефоне — свайпы": "on mobile — swipes",
 "на телефоне — тап": "on mobile — tap",
 "набирает": "draws",
 "нажать кнопку": "press the button",
 "нот)": "notes)",
 "огонь": "fire",
 "один клик": "one tap",
 "одна кнопка": "one button",
 "открыть": "reveal",
 "открыть соседей": "chord neighbors",
 "отмена хода": "undo",
 "отменить": "undo",
 "память": "memory",
 "память · звук": "memory · sound",
 "память чисел": "number memory",
 "пауза": "pause",
 "платформа": "paddle",
 "побед": "wins",
 "победа": "win",
 "победы": "wins",
 "поворот": "rotate",
 "поп.": "tries.",
 "попытка": "try",
 "попытки": "tries",
 "попыток": "tries",
 "поставить знак": "place a mark",
 "пригнуться": "duck",
 "пройден за": "cleared in",
 "против ИИ": "vs AI",
 "прыжки": "jumps",
 "прыжок": "jump",
 "разгадано!": "cracked!",
 "ракетка": "paddle",
 "раннер": "runner",
 "реакция": "reaction",
 "с": "s",
 "с штрафа)": "s penalty)",
 "сброс": "drop",
 "свайпы": "swipes",
 "сдвиг": "shift",
 "сдвинуть фишку": "slide a tile",
 "скорость": "speed",
 "ставка": "bet",
 "стакан 10×20": "10×20 well",
 "стрельба · группы": "shooter · groups",
 "тактика": "tactics",
 "тап по полосе на телефоне": "tap a lane on mobile",
 "тап — прыжок · свайп вниз — пригнуться": "tap — jump · swipe down — duck",
 "твой ход": "your move",
 "точность": "precision",
 "тяга": "thrust",
 "удержать": "hold",
 "уклонение": "dodging",
 "уровень": "level",
 "уровней пройдено": "levels cleared",
 "ускорить": "faster",
 "физика": "physics",
 "флажок": "flag",
 "ход": "move",
 "ход.": "move.",
 "хода": "moves",
 "ходов": "moves",
 "шире платформа": "wider paddle",
 "— Игротека": "— Igroteka",
 "← Игры": "← Games",
 "← → / A D — смена полосы": "← → / A D — change lane",
 "← → / мышь / палец — движение": "← → / mouse / finger — move",
 "← → движение": "← → move",
 "← → движение · Пробел — огонь": "← → move · Space — fire",
 "← → или тап по полосе — смена полосы, ↑ — ускориться, ↓ — притормозить.\nСкорость растёт сама, машины едут навстречу — обгоняй поток как можно дольше.\nСчёт — пройденные метры. Любое касание — авария.": "← → or tap a lane — change lanes, ↑ — speed up, ↓ — slow down.\nThe speed grows on its own, cars come at you head-on — overtake the traffic for as long as you can.\nYour score is meters driven. Any touch is a crash.",
 "← → поворот · ↑ тяга": "← → rotate · ↑ thrust",
 "← → поворот · ↑ тяга · Пробел — огонь": "← → rotate · ↑ thrust · Space — fire",
 "← → поворот модуля, ↑ — двигатель (жжёт топливо).": "← → tilt the module, ↑ — engine (burns fuel).",
 "← → — движение, Пробел — выстрел (не больше трёх в воздухе). Тап по краям экрана — движение, по центру — огонь.\nРой движется из стороны в сторону и спускается. Чем меньше пришельцев, тем быстрее рой — не дайте им приземлиться.\nПришельцы стреляют в ответ. Три попадания по тебе или приземление роя — конец.\nВерхние ряды дороже: 50/40/30/20/10 очков. Волны сменяют друг друга бесконечно.": "← → — move, Space — fire (no more than three shots in the air). Tap the screen edges to move, the center to fire.\nThe swarm slides side to side and descends. The fewer aliens remain, the faster the swarm — don’t let them land.\nThe aliens shoot back. Three hits on you or a landed swarm — game over.\nTop rows are worth more: 50/40/30/20/10 points. Waves replace each other endlessly.",
 "← → — движение, ↑ — поворот, ↓ — ускорить, Пробел — мгновенный сброс, C — отложить фигуру в «Удержание».\nЗаполни ряд целиком — он сгорает: 1/2/3/4 линии дают 100/300/500/800 очков × уровень. Четыре линии разом — «ТЕТРИС»!\nТонкая рамка под фигурой — «призрак»: показывает, куда она упадёт.\nКаждые 10 линий — новый уровень и рост скорости.\nИгра кончается, когда новая фигура не помещается в стакан.": "← → — move, ↑ — rotate, ↓ — soft drop, Space — hard drop, C — park the piece in “Hold”.\nFill a full row and it burns: 1/2/3/4 lines give 100/300/500/800 points × level. Four lines at once — “TETRIS”!\nThe thin outline under the piece is the ghost: it shows where the piece will land.\nEvery 10 lines — a new level and more speed.\nThe game ends when the next piece no longer fits in the well.",
 "← → — поворот модуля, ↑ — двигатель (жжёт топливо).\nЦель — жёлтая площадка: скорость снижения ≤ 55, боковой снос ≤ 30, корпус вертикально.\nМягкая посадка даёт очки + бонус за плавность и остаток топлива. Сади сериями — счёт копится.\nМимо площадки, слишком быстро или на бок — крах.": "← → — tilt the module, ↑ — engine (burns fuel).\nThe goal is the yellow pad: descent speed ≤ 55, sideways drift ≤ 30, body vertical.\nA soft landing scores points plus bonuses for smoothness and remaining fuel. Land in series — the score adds up.\nOff the pad, too fast or sideways — a crash.",
 "← → — поворот, ↑ — тяга (корабль скользит по инерции!), Пробел — выстрел, P — пауза.\nБольшой астероид распадается на два средних, средний — на два малых. Мелкие дают больше очков (100).\nСтолкновение отнимает корабль (их три); после гибели — пара секунд неуязвимости.\nРасчистил поле — новая волна: камней больше и они быстрее.": "← → — rotate, ↑ — thrust (the ship glides with inertia!), Space — fire, P — pause.\nA large asteroid splits into two medium ones, a medium one into two small ones. Small rocks score more (100).\nA collision costs a ship (you have three); after dying you get a couple of seconds of invincibility.\nClear the field — a new wave: more rocks, and they move faster.",
 "↑ быстрей · ↓ медленней": "↑ faster · ↓ slower",
 "↑ ↓ угол · ← → сила · Пробел — огонь": "↑ ↓ angle · ← → power · Space — fire",
 "↑ ↓ — угол ствола, ← → — сила, Пробел — огонь. На телефоне: левая часть экрана — угол, правая — сила, центр — огонь.\nСтрелка сверху показывает ветер — он сносит снаряд в полёте и меняется после каждого выстрела.\nПопади по красной пушке раньше, чем ИИ попадёт по тебе. ИИ целится с погрешностью — шансы есть всегда.": "↑ ↓ — barrel angle, ← → — power, Space — fire. On mobile: left half — angle, right — power, center — fire.\nThe arrow at the top shows the wind — it pushes the shell in flight and changes after every shot.\nHit the red cannon before the AI hits you. The AI aims with an error margin — you always have a chance.",
 "↩ Отмена (Z)": "↩ Undo (Z)",
 "↩ Отменить": "↩ Undo",
 "↩ Отменить ход": "↩ Undo move",
 "⌨️ ПЕЧАТЬ": "⌨️ TYPING",
 "▶ Играть": "▶ Play",
 "☄️ МЕТЕОРЫ": "☄️ METEORS",
 "⚡ РЕАКЦИЯ": "⚡ REACTION",
 "⚪ ИИ": "⚪ AI",
 "⚫ Вы": "⚫ You",
 "⚫ ГОМОКУ": "⚫ GOMOKU",
 "⚫ РЕВЕРСИ": "⚫ REVERSI",
 "✕ стереть": "✕ erase",
 "✨ Золотой крот = +3 очка": "✨ Golden mole = +3 points",
 "⭕ КРЕСТИКИ": "⭕ TIC-TAC-TOE",
 "🃏 ОЧКО": "🃏 BLACKJACK",
 "🃏 ПАРА": "🃏 MEMORY",
 "🌈 ПОТОК": "🌈 FLOW",
 "🌕 ЛУНА": "🌕 LUNAR LANDER",
 "🎨 СТРУП": "🎨 STROOP",
 "🎯 2048": "🎯 2048",
 "🎯 АИМ": "🎯 AIM TRAINER",
 "🎯 ВИСЕЛИЦА": "🎯 HANGMAN",
 "🎵 МЕЛОДИЯ": "🎵 SIMON",
 "🏆 Новый рекорд!": "🏆 New record!",
 "🏆 ПОБЕДА!": "🏆 YOU WIN!",
 "🏆 Первая победа над ИИ!": "🏆 First win against the AI!",
 "🏆 Первая победа!": "🏆 First win!",
 "🏆 банк": "🏆 bank",
 "🏆 время:": "🏆 time:",
 "🏆 уровень": "🏆 level",
 "🏎️ ПРОБКА": "🏎️ TRAFFIC",
 "🏒 АЭРОХОККЕЙ": "🏒 AIR HOCKEY",
 "🏓 ПОНГ": "🏓 PONG",
 "🏗️ БАШНЯ": "🏗️ STACK TOWER",
 "🐄 БЫКИ И КОРОВЫ": "🐄 BULLS & COWS",
 "🐍 ЗМЕЙКА": "🐍 SNAKE",
 "🐦 FLAPPY": "🐦 FLAPPY",
 "👾 ИНВЕЙДЕРЫ": "👾 INVADERS",
 "💎 ТРИ-В-РЯД": "💎 MATCH 3",
 "💡 ВЫКЛЮЧИ СВЕТ": "💡 LIGHTS OUT",
 "💣 САПЁР": "💣 MINESWEEPER",
 "💥 ПУШКА": "💥 ARTILLERY",
 "📜 Правила": "📜 Rules",
 "📦 СОКОБАН": "📦 SOKOBAN",
 "🔐 КОД": "🔐 CODEBREAKER",
 "🔗 ТОЧКИ": "🔗 DOTS & BOXES",
 "🔟 СУДОКУ": "🔟 SUDOKU",
 "🔢 ПЯТНАШКИ": "🔢 15 PUZZLE",
 "🔢 ЦЕПОЧКА": "🔢 NUMBER SPAN",
 "🔤 СЛОВО": "🔤 WORDLY",
 "🔥 Каскад": "🔥 Cascade",
 "🔥 Серия:": "🔥 Streak:",
 "🔨 КРОТЫ": "🔨 WHACK-A-MOLE",
 "🔵 СОЕДИНИ 4": "🔵 CONNECT 4",
 "🕹️ АРКАНОИД": "🕹️ BREAKOUT",
 "🕹️ ИГРОТЕКА": "🕹️ IGROTEKA",
 "🗼 ХАНОЙ": "🗼 TOWER OF HANOI",
 "🚀 АСТЕРОИДЫ": "🚀 ASTEROIDS",
 "🚁 ВЕРТОЛЁТ": "🚁 COPTER",
 "🚢 МОРСКОЙ БОЙ": "🚢 BATTLESHIP",
 "🟢 ПОЖИРАТЕЛЬ": "🟢 ORBS",
 "🟢 на месте · 🟡 есть, но не здесь": "🟢 right spot · 🟡 present, wrong place",
 "🥁 РИТМ": "🥁 RHYTHM",
 "🥢 НИМ": "🥢 NIM",
 "🦖 ДИНО": "🦖 DINO",
 "🦘 ДУДЛ": "🦘 DOODLE",
 "🧮 СЧЁТ": "🧮 MATH SPRINT",
 "🧱 ТЕТРИС": "🧱 TETRIS",
 "🫘 МАНКАЛА": "🫘 MANCALA",
 "🫧 ПУЗЫРИ": "🫧 BUBBLES"
},
  rules: 
  [
    [/^🏆 (\d+) (победа|победы|побед)$/, (m, n) => +n === 1 ? '🏆 1 win' : `🏆 ${n} wins`, 1],
    [/^🏆 (\d+) (ход|хода|ходов)$/, (m, n) => +n === 1 ? '🏆 1 move' : `🏆 ${n} moves`, 1],
    [/^🏆 (\d+) (попытка|попытки|попыток)$/, (m, n) => +n === 1 ? '🏆 1 try' : `🏆 ${n} tries`, 1],
    [/^🏆 (\d+) поп\.$/, '🏆 $1 tries'],
    [/^🏆 (\d+) м$/, '🏆 $1 m'],
    [/^🏆 (\d+) мс$/, '🏆 $1 ms'],
    [/^🏆 (\d+) з\/м$/, '🏆 $1 cpm'],
    [/^🏆 ([\d.,]+) с$/, '🏆 $1 s'],
    [/^🏆 уровень (\d+)$/, '🏆 level $1'],
    [/^🏆 время: (.+)$/, '🏆 time: $1'],
    [/^🏆 банк (\d+)$/, '🏆 bank $1'],
    [/^(\d+) : (\d+) в твою пользу$/, '$1 : $2 in your favor'],
    [/^(\d+) : (\d+) — больше квадратов у тебя$/, '$1 : $2 — more boxes, you!'],
    [/^ИИ собрал больше: (\d+) : (\d+)$/, 'AI collected more: $1 : $2'],
    [/^Счёт сессии: вы (\d+) : (\d+) ИИ · ничьи (\d+)$/, 'Session: you $1 : $2 AI · draws $3'],
    [/^🔥 Серия: (\d+)$/, '🔥 Streak: $1'],
    [/^🔥 Каскад ×(\d+)$/, '🔥 Cascade ×$1'],
    [/^🔥 Каскад (\d+)$/, '🔥 Cascade $1'],
    [/^ТЕТРИС! \+(\d+)$/, 'TETRIS! +$1'],
    [/^Все уровни пройдены! Последний — за (.+)$/, 'All levels cleared! The last one — $1'],
    [/^Слишком быстро: (.+)$/, 'Too fast: $1'],
    [/^Не угадали\. Слово: (.+)$/, 'No luck. The word: $1'],
    [/^Слово было: (.+)$/, 'The word was: $1'],
    [/^Слово: (.+)$/, 'Word: $1'],
    [/^Верно! Уровень (\d+)$/, 'Correct! Level $1'],
    [/^Средняя реакция: (.+)$/, 'Average reaction: $1'],
    [/^Твой ход — повтори \((\d+) нот\)$/, 'Your turn — repeat ($1 notes)'],
    [/^Твой ход — повтори \((\d+) нот.\)$/, 'Your turn — repeat ($1 notes)'],
    [/^Ошибок: (\d+) из (\d+)$/, 'Mistakes: $1 of $2'],
    [/^(\d+) с$/, '$1 s'],
    [/^(\d+) км\/ч$/, '$1 km/h'],
    [/^Угол (\d+)°\s*·\s*Сила (\d+)$/, 'Angle $1° · Power $2'],
    [/^Ветер: (.+)$/, 'Wind: $1'],
    [/^Дилер — (.+)$/, 'Dealer — $1'],
    [/^Дилер: (\d+)$/, 'Dealer: $1'],
    [/^Ты — (\d+)$/, 'You: $1'],
    [/^Ты — (.+)$/, 'You — $1'],
    [/^Минимум ходов: (\d+)$/, 'Minimum moves: $1'],
    [/^Ходы: (\d+)$/, 'Moves: $1'],
    [/^Время: (.+)$/, 'Time: $1'],
    [/^Уровень (\d+)$/, 'Level $1'],
    [/^(\d+) из (\d+)$/, '$1 of $2'],
    [/^(\d+) нот\)$/, '$1 notes)'],
    [/^Уровень (\d+) пройден за (\d+) ходов$/, 'Level $1 cleared in $2 moves'],
    [/^Все уровни пройдены! Последний — за (\d+) ходов$/, 'All levels cleared! The last one — $1 moves'],
    [/^Время: (.+) · открыто (\d+)% поля$/, 'Time: $1 · open $2% of the field'],
    [/^· открыто (\d+) из (\d+)$/, '· open $1 of $2'],
    [/^· ходов (\d+)$/, '· moves $1'],
    [/^Ряд (\d+) — (\d+)$/, 'Row $1 — $2'],
  ]

};
